general.import = [
  # my configs
  #"~/dotfiles/themes/current/alacritty.toml"
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Medium" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono  Nerd Font", style = "Italic" }
size = 12

[window]
padding.x = 20
padding.y = 20
decorations = "none"
opacity = 0.95

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
